### ISSUE TITLE
Controlling Light/Switches Support?

### ISSUE THREAD

**Issue by ghost** [haruny/adt-pulse-mqtt#13] opened 2018-08-09 03:17 UTC

**Comment by haruny** [comment] 2018-08-09 03:50
I don’t have lights/switches so I’ll need help. 

Could you provide me the url of page that you can turn on/off light? I’ll also need the content of the page and the resultant page, if any. 
I don’t have lights/switches so I’ll need help.

**Comment by haruny** [comment] 2018-08-09 03:50
Duplicate of #11

**Closed as completed by haruny** 2018-08-09 03:50 UTC
