### ISSUE TITLE
::TypeError: Cannot read property '1' of null (again)

### ISSUE THREAD

**Issue by JamesValero** [haruny/adt-pulse-mqtt#36] opened 2020-04-20 07:09 UTC
Seems like ADT may have done another update. I'm unable to trigger any sensors or enable/disable the alarm.

Below is what I see in the addon logs
```html
<div class="p_footerShim2"></div>



</body>
</html>



::TypeError: Cannot read property '1' of null
```

**Comment by digitalcraig** [comment] 2020-04-20 13:53
Are you still getting this? Mine is working as of this morning.

**Comment by JamesValero** [comment] 2020-04-23 07:03
Yes. I also tried to uninstall/reinstall and have the same issue. 

These are all the lines I see in the log. If you need the full source, let me know if there's anything else you'd need me to do other than logging to pulse with my browser > view source > copy/paste.
```html
      <img src="/myhome/18.0.0-78/images/spacer.gif" border=0 width="1" height="15">

            <div id="schedtop" class="p_sumgrowboxtop"></div>
            <div id="schedmid" class="p_sumgrowboxmid">
                <span class="p_summaryboxtitle"><a href="/myhome/18.0.0-78/schedule/schedule.jsp">Today's Schedule</a></span>
                <div id="divScheduleContent" class="p_summaryboxcontent">
                    





    <table border="0" cellspacing=0 cellpadding=0>
        <tr>
            <td>
                <table class="p_rowl" border=0 cellpadding=0 cellspacing=0 width=325>
<tr><td width=100% class="listBoxData">
<div id="todaysScheduleList" style="height:114px;position:relative;overflow:auto;overflow-y:auto;overflow-x:auto;text-align:left;">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width=11 class='p_iconCellSummary'><img src="/myhome/18.0.0-78/images/spacer.gif" vspace=0 hspace=5 width=11 height=10 border=0 style="margin-top:3px;"></td><td rowspan=2 class='p_listRow'>None scheduled for today.</td></tr></table></td></tr>
<tr class="p_rowd"><td width="100%" height="19">&nbsp;</td></tr>
<tr class="p_rowl"><td width="100%" height="19">&nbsp;</td></tr>
<tr class="p_rowd"><td width="100%" height="19">&nbsp;</td></tr>
<tr class="p_rowl"><td width="100%" height="19">&nbsp;</td></tr>
<tr class="p_rowd"><td width="100%" height="19">&nbsp;</td></tr>

</table>
</div>
</tr>
</table>

            </td>
        </tr>
    </table>


                </div>
            </div>
            <div id="schedbot" class="p_sumgrowboxbot"></div>
            <img src="/myhome/18.0.0-78/images/spacer.gif" border=0 width="1" height="15">

        </td>
    </tr>

</table>


     
     <div style="height:8px;"></div>
     <div id="customize"><a class="p_normalText" href="/myhome/18.0.0-78/myaccount/myaccount.jsp">Customize this page</a></div>
     

  </div>

  
  <div id="footer_extension" class="p_footerExtension"></div>

  </div>  



  <div class="p_footerShim">
      <div id="links" align="center" class="p_footerStyle ">
        <a class="p_footerLink" href="http://www.adt.com" target="_blank">ADT Security Services</a>
            <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/about-adt/legal/pulse-portal-privacy" target="_blank">Privacy Policy</a>
            <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/about-adt/legal/adt-pulse-terms-of-use" target="_blank">Terms of Use</a>
            <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/help" target="_blank">Customer Support</a>
            <span class="p_footerDivider"> | </span>
        <a class="p_footerLink" href="#" onclick="javascript:window.setTimeout(function(){openModalDialog('/myhome/18.0.0-78/help/versionInfo.jsp', 662, 470, {autoCloseable: 'yes', closeBox: 'no'} );},100)">About<!--About--></a>
      </div>
      <span class="p_footerWrapper" style="display:inline;visibility:visible">
         <a href="#" onclick="javascript:window.setTimeout(function(){openModalDialog('/myhome/18.0.0-78/help/versionInfo.jsp', 662, 380, {autoCloseable: 'yes', closeBox: 'no'} );},100)" style="position:relative; top:-16px; margin-right:8px;">
            
            <!-- todo localization - poweredby_logo contains text "powered by" in the image -->
            <div id="poweredby_logo" style="visibility:visible;width:90px;height:20px;cursor:pointer;"></div>
         </a>
      </span>

  
          
          <div class="p_footerLegal1">Your use of this site signifies that you accept the ADT Pulse Website Terms of Use Agreement.</div>
      
          
          <div class="p_footerLegal2">&copy;2018 ADT LLC dba ADT Security Services. All rights reserved. ADT, the ADT logo, 800.ADT.ASAP and the product/service names listed in this document are marks and/or registered marks. Unauthorized use is strictly prohibited. Unauthorized use of this site is prohibited and may be subject to civil and criminal prosecution.</div>
      
      <div class="floatstop"></div>
  </div>
</div>  

<div class="p_footerShim2"></div>



</body>
</html>



::TypeError: Cannot read property '1' of null
```

**Comment by digitalcraig** [comment] 2020-04-23 13:48
My ADT Pulse is pointing to the same version as yours - /myhome/18.0.0-78/summary/summary.jsp and it's working. I don't think there was a new version of the Pulse. Please verify that your add-on is version 2.2.11 (package.json).

**Comment by JamesValero** [comment] 2020-04-23 19:38
Yes, same version. I'm going to try to reinstall and manually re-enter my
details instead of copy/paste from the previous configuration.

**Comment by JamesValero** [comment] 2020-04-23 20:06
Same error. Thanks a lot for helping me out!

Uninstalled
Removed Repo
Added Repo back (https://github.com/digitalcraig/adt-pulse-mqtt)
Reinstalled (0.2.2.11)
Added login to the config
Started
Got the same error

Is there anything wrong with my config settings that can be causing the TypeError?

```yaml
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
pulse_login:
  username: user@email.com
  password: 'mysecretpassword'
mqtt_host: core-mosquitto
mqtt_url: ''
mqtt_connect_options:
  username: mqtt
  password: 'myOtherPassword'
alarm_state_topic: home/alarm/state
alarm_command_topic: home/alarm/cmd
zone_state_topic: adt/zone
smartthings_topic: smartthings
smartthings: false
```

**Comment by digitalcraig** [comment] 2020-04-24 12:13
Switch your repo to https://github.com/haruny/adt-pulse-mqtt and see if you get a different result. He's bumped his version number to 2.3.0. 

My repo is intended to be used as a standalone Docker container. If you use it with as a Hassio add-on, it's better to use https://github.com/haruny/adt-pulse-mqtt.

**Comment by JamesValero** [comment] 2020-04-24 14:58
That fixed it! Thanks

**Comment by digitalcraig** [comment] 2020-04-24 15:19
Good, I suspect the issue is that I used a bad version number in a previous update and it was fixed in one place but another. I don't think it was seeing that a newer version was published and it was still using the older Docker image instead of building a new one.

I will update my version number to 2.3.0 as well and that should fix it for anyone else still using my repo.

**Closed as completed by digitalcraig** 2020-04-24 15:19 UTC
